#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-sass
Version  : 3.4.22
Release  : 11
URL      : https://rubygems.org/downloads/sass-3.4.22.gem
Source0  : https://rubygems.org/downloads/sass-3.4.22.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-sass-bin
BuildRequires : ruby
BuildRequires : rubygem-maruku
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-yard

%description
# Sass [![Gem Version](https://badge.fury.io/rb/sass.png)](http://badge.fury.io/rb/sass) [![Inline docs](http://inch-ci.org/github/sass/sass.svg)](http://inch-ci.org/github/sass/sass)

%package bin
Summary: bin components for the rubygem-sass package.
Group: Binaries

%description bin
bin components for the rubygem-sass package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n sass-3.4.22
gem spec %{SOURCE0} -l --ruby > rubygem-sass.gemspec

%build
gem build rubygem-sass.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
sass-3.4.22.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/sass-3.4.22
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/sass-3.4.22.gem
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/CODE_OF_CONDUCT.md
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/README.md
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/REVISION
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/VERSION_DATE
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/VERSION_NAME
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/bin/sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/bin/sass-convert
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/bin/scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/extra/update_watch.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/init.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/cache_stores.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/cache_stores/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/cache_stores/chain.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/cache_stores/filesystem.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/cache_stores/memory.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/cache_stores/null.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/css.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/exec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/exec/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/exec/sass_convert.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/exec/sass_scss.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/features.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/importers.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/importers/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/importers/deprecated_path.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/importers/filesystem.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/logger/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/logger/log_level.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/media.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/compiler.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/generic.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/merb.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/rack.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/repl.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/root.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/css_lexer.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/css_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/css_variable_warning.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/functions.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/lexer.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/funcall.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/interpolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/list_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/map_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/string_interpolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/unary_operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/tree/variable.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/arg_list.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/bool.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/color.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/list.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/map.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/null.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/number.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/script/value/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/scss.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/scss/css_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/scss/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/scss/rx.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/scss/static_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/selector/abstract_sequence.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/selector/comma_sequence.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/selector/pseudo.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/selector/sequence.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/selector/simple.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/selector/simple_sequence.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/shared.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/source/map.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/source/position.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/source/range.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/stack.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/supports.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/at_root_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/charset_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/comment_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/content_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/css_import_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/debug_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/directive_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/each_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/error_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/extend_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/for_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/function_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/if_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/import_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/keyframe_rule_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/media_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/mixin_def_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/mixin_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/prop_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/return_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/root_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/rule_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/supports_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/trace_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/variable_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/check_nesting.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/convert.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/cssize.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/deep_copy.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/extend.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/set_options.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/to_css.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/warn_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/tree/while_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/util.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/util/cross_platform_random.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/util/multibyte_string_scanner.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/util/normalized_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/util/ordered_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/util/subset_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/util/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/lib/sass/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/rails/init.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass-spec.yml
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/cache_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/callbacks_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/compiler_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/conversion_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/css2sass_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/css_variable_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/data/hsl-rgb.txt
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/encoding_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/engine_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/exec_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/extend_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/fixtures/test_staleness_check_across_importers.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/fixtures/test_staleness_check_across_importers.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/functions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/importer_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/logger_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/mock_importer.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/more_results/more1.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/more_results/more1_with_line_comments.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/more_results/more_import.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/more_templates/_more_partial.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/more_templates/more1.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/more_templates/more_import.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/plugin_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/alt.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/basic.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/cached_import_option.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/compact.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/complex.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/compressed.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/expanded.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/filename_fn.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/if.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/import.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/import_charset.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/import_charset_1_8.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/import_charset_ibm866.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/import_content.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/line_numbers.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/mixins.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/multiline.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/nested.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/options.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/parent_ref.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/script.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/scss_import.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/scss_importee.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/subdir/nested_subdir/nested_subdir.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/subdir/subdir.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/units.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/warn.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/results/warn_imported.css
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/script_conversion_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/script_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/scss/css_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/scss/rx_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/scss/scss_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/scss/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/source_map_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/superselector_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/_cached_import_option_partial.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/_double_import_loop2.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/_filename_fn_import.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/_imported_charset_ibm866.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/_imported_charset_utf8.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/_imported_content.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/_partial.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/_same_name_different_partiality.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/alt.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/basic.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/bork1.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/bork2.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/bork3.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/bork4.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/bork5.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/cached_import_option.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/compact.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/complex.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/compressed.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/double_import_loop1.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/expanded.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/filename_fn.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/if.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/import.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/import_charset.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/import_charset_1_8.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/import_charset_ibm866.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/import_content.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/importee.less
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/importee.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/line_numbers.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/mixin_bork.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/mixins.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/multiline.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/nested.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/nested_bork1.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/nested_bork2.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/nested_bork3.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/nested_bork4.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/nested_import.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/nested_mixin_bork.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/options.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/parent_ref.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/same_name_different_ext.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/same_name_different_ext.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/same_name_different_partiality.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/script.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/scss_import.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/scss_importee.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/single_import_loop.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/subdir/import_up1.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/subdir/import_up2.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/subdir/nested_subdir/_nested_partial.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/subdir/nested_subdir/nested_subdir.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/subdir/subdir.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/units.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/warn.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/templates/warn_imported.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/util/multibyte_string_scanner_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/util/normalized_map_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/util/subset_map_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/util_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/sass/value_helpers_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/README.md
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/Vagrantfile
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapters/bsd.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapters/darwin.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapters/linux.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapters/polling.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapters/windows.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/directory_record.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/listener.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/turnstile.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/listen.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen/adapter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen/adapters/bsd_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen/adapters/darwin_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen/adapters/linux_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen/adapters/polling_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen/adapters/windows_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen/directory_record_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen/listener_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen/turnstile_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/listen_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/support/adapter_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/support/directory_record_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/support/fixtures_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/support/listeners_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-3.4.22/vendor/listen/spec/support/platform_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/sass-3.4.22.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/sass
/usr/bin/sass-convert
/usr/bin/scss
